apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: test-ci-cd-pipeline
description: application deployment pipeline
serialPipeline:
 stages:
 - targetId: dev-env
   profiles:
   - dev
 - targetId: test-env
   profiles:
   - test
 - targetId: prod-env
   profiles:
   - prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-env
description: Cloud Run development service
run:
 location: projects/$PROJECT_ID/locations/$_DEPLOY_REGION
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test-env
description: Cloud Run test service
run:
 location: projects/$PROJECT_ID/locations/$_DEPLOY_REGION
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-env
description: Cloud Run prod service
run:
 location: projects/$PROJECT_ID/locations/$_DEPLOY_REGION